"""Day88 application-owned boundary for replaceable Agent frameworks.

Framework output is only an untrusted proposal.  Production Tool clients are
deliberately absent from framework adapters and remain behind ``Committer``.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping, Protocol


class Outcome(str, Enum):
    COMPLETED = "COMPLETED"
    DENIED = "DENIED"
    INVALID = "INVALID"
    REPLAY = "REPLAY"
    CONFLICT = "CONFLICT"
    PENDING_RECONCILIATION = "PENDING_RECONCILIATION"


@dataclass(frozen=True)
class ToolProposal:
    """Strict application DTO; it contains no framework-owned state."""

    tool_name: str
    amount_minor: int
    currency: str


@dataclass(frozen=True)
class ProposalEnvelope:
    """Trusted metadata owned by the application, never generated by a model."""

    operation_id: str
    attempt_id: str
    approval_id: str
    fence_token: int
    policy_version: int
    deadline_ms: int


@dataclass(frozen=True)
class CurrentFacts:
    """Current authoritative facts re-read immediately before dispatch."""

    operation_id: str
    grant_active: bool
    approval_id: str
    approval_intent_hash: str
    fence_token: int
    policy_version: int
    now_ms: int
    cancelled: bool = False


@dataclass(frozen=True)
class FrameworkToolCall:
    """Minimal framework output accepted by the selected Adapter."""

    tool_name: str
    arguments: Mapping[str, Any]


class FrameworkAdapter(Protocol):
    """Replaceable boundary; implementations cannot receive a Tool client."""

    adapter_id: str

    def to_proposal(self, output: FrameworkToolCall) -> ToolProposal:
        """Convert untrusted framework output into an application DTO."""


class ProposalValidationError(ValueError):
    pass


class AmbiguousToolResult(RuntimeError):
    """The Tool may have committed a side effect but its response is unknown."""


class ProductionTool(Protocol):
    def invoke(
        self,
        *,
        operation_id: str,
        proposal: ToolProposal,
    ) -> Mapping[str, Any]: ...


def canonical_intent_hash(proposal: ToolProposal) -> str:
    payload = {
        "amount_minor": proposal.amount_minor,
        "currency": proposal.currency,
        "tool_name": proposal.tool_name,
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


@dataclass
class CommitAudit:
    outcome: Outcome
    operation_id: str
    reasons: tuple[str, ...] = ()
    validators_executed: tuple[str, ...] = ()
    tool_called: bool = False
    durable_transition: bool = False
    replayed_result: Mapping[str, Any] | None = None


@dataclass
class Committer:
    """Application-owned validator and the only holder of a Tool client."""

    tool: ProductionTool
    completed: dict[str, tuple[str, Mapping[str, Any]]] = field(default_factory=dict)
    durable_state: dict[str, Outcome] = field(default_factory=dict)
    evidence_inbox: list[Mapping[str, Any]] = field(default_factory=list)

    VALIDATORS = (
        "operation_id",
        "tool_registration",
        "grant",
        "policy_version",
        "fence",
        "approval_id",
        "approval_binding",
        "deadline",
        "cancellation",
    )

    def process(
        self,
        adapter: FrameworkAdapter,
        output: FrameworkToolCall,
        envelope: ProposalEnvelope,
        facts: CurrentFacts,
    ) -> CommitAudit:
        try:
            proposal = adapter.to_proposal(output)
        except (ProposalValidationError, TypeError, ValueError):
            return CommitAudit(
                Outcome.INVALID,
                envelope.operation_id,
                reasons=("output_validation_failure",),
            )

        proposal_hash = canonical_intent_hash(proposal)
        previous = self.completed.get(envelope.operation_id)
        if previous is not None:
            previous_hash, previous_result = previous
            if previous_hash == proposal_hash:
                return CommitAudit(
                    Outcome.REPLAY,
                    envelope.operation_id,
                    reasons=("duplicate",),
                    replayed_result=previous_result,
                )
            return CommitAudit(
                Outcome.CONFLICT,
                envelope.operation_id,
                reasons=("duplicate_payload_conflict",),
            )

        checks = {
            "operation_id": envelope.operation_id == facts.operation_id,
            "tool_registration": proposal.tool_name == "refund",
            "grant": facts.grant_active,
            "policy_version": envelope.policy_version == facts.policy_version,
            "fence": envelope.fence_token == facts.fence_token,
            "approval_id": envelope.approval_id == facts.approval_id,
            "approval_binding": proposal_hash == facts.approval_intent_hash,
            "deadline": facts.now_ms <= envelope.deadline_ms,
            "cancellation": not facts.cancelled,
        }
        reason_names = {
            "operation_id": "operation_id_mismatch",
            "tool_registration": "unregistered_tool",
            "grant": "grant_revoked",
            "policy_version": "stale_policy",
            "fence": "stale_fence",
            "approval_id": "approval_id_mismatch",
            "approval_binding": "approval_argument_mismatch",
            "deadline": "deadline_expired",
            "cancellation": "cancelled",
        }
        reasons = tuple(
            reason_names[name] for name in self.VALIDATORS if not checks[name]
        )
        if reasons:
            return CommitAudit(
                Outcome.DENIED,
                envelope.operation_id,
                reasons=reasons,
                validators_executed=self.VALIDATORS,
            )

        try:
            result = self.tool.invoke(
                operation_id=envelope.operation_id,
                proposal=proposal,
            )
        except AmbiguousToolResult:
            self.durable_state[envelope.operation_id] = (
                Outcome.PENDING_RECONCILIATION
            )
            return CommitAudit(
                Outcome.PENDING_RECONCILIATION,
                envelope.operation_id,
                reasons=("tool_result_unknown",),
                validators_executed=self.VALIDATORS,
                tool_called=True,
                durable_transition=True,
            )

        self.completed[envelope.operation_id] = (proposal_hash, result)
        self.durable_state[envelope.operation_id] = Outcome.COMPLETED
        return CommitAudit(
            Outcome.COMPLETED,
            envelope.operation_id,
            validators_executed=self.VALIDATORS,
            tool_called=True,
            durable_transition=True,
        )

    def submit_observation(
        self,
        *,
        operation_id: str,
        observer_fence: int,
        result: str,
        source: str,
    ) -> None:
        self.evidence_inbox.append({
            "operation_id": operation_id,
            "observer_fence": observer_fence,
            "result": result,
            "source": source,
        })

    def reconcile_success(
        self,
        *,
        facts: CurrentFacts,
        submitter_fence: int,
    ) -> bool:
        if submitter_fence != facts.fence_token:
            return False
        if self.durable_state.get(facts.operation_id) is Outcome.CONFLICT:
            return False
        self.durable_state[facts.operation_id] = Outcome.COMPLETED
        return True
